### ISSUE TITLE
Upload Error Invalid response: CODE 413

### ISSUE THREAD

**Issue by jtande** [jtande/jupyterhub#1]
This happens when user's try to upload files that are larger than the default limit (512b) on the proxy server.

## Solution
Adding nginx.ingress.kubernetes.io/proxy-body-size: 128m
```
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-body-size: 128m
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - ism210-jhub.eastus.cloudapp.azure.com
```

## References
- https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/
- https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#custom-max-body-size
- http://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size
- https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1230
